### ISSUE TITLE
ngram is broken in dfm function

### ISSUE THREAD

**Issue by smbatchou** [kbenoit/quanteda#178] opened 2016-05-24 19:03 UTC
> dfm(CORPUS_ENG,ngrams=2)
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 93,315 documents
   ... indexing features: 123,536 feature types
Error in validObject(r) : 
  invalid class “dgTMatrix” object: length(Dimnames[2]) differs from Dim[2] which is 422238

**Comment by adamobeng** [comment] 2016-05-24 19:17
Hi @smbatchou. Could you give us the output of  `sessionInfo()`, please?

**Comment by adamobeng** [comment] 2016-05-24 19:17
Hi @smbatchou, could you give us the output of `sessionInfo()`, please?

**Comment by kbenoit** [comment] 2016-05-24 20:02
This looks like the error that was caused by empty (zero token) documents, fixed in the latest CRAN release. Please update and try again.

**Comment by smbatchou** [comment] 2016-05-25 14:48
Hi @kbenoit Actually this error started to happened I updated to the last cran version..
Hi @adamobeng here is the sessionInfo()
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.6-9

loaded via a namespace (and not attached):
 [1] Matrix_1.2-4     parallel_3.2.4   tools_3.2.4      Rcpp_0.12.4      stringi_1.0-1    grid_3.2.4       data.table_1.9.6 chron_2.3-47     lattice_0.20-33  ca_0.64         
> 


Thanks

**Comment by kbenoit** [comment] 2016-05-29 09:46
OK - try the GitHub release, >= 0.9.7, and let us know if the problem is still there.

**Comment by smbatchou** [comment] 2016-06-02 20:10
Hi @kbenoit I think the package is working fine. The issue might be somewhere in my dataset
Thank again for the great package

**Closed** 2016-06-08 17:19 UTC
