### ISSUE TITLE
dfm does not work or takes very long time when corpus is large

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#375] opened 2016-12-17 15:27 UTC
```
> tok <- tokens(data_corpus_guardian)
> system.time(dfm(tok))
Timing stopped at: 2031.688 1.916 2034.771
```

**Comment by koheiw** [comment] 2016-12-21 22:16
It was caused by tokens methods. If x in compile_dfm.tokensis unclassed, the time became reasonable. 
```
Creating a dfm from a tokens object ...
   ... lowercasing
   ... found 177,115 documents, 388,894 features
   ... created a 177,115 x 388,894 sparse dfm
   ... complete. 
Elapsed time: 88.7 seconds.
```
We have to be very careful about tokens methods such as [] and [[]]. When these are triggered by internal functions, they slow down over 1000 times.

**Comment by koheiw** [comment] 2016-12-21 22:23
It is probably the time for @HaiyanLW to write dfm with RcppParallel.

**Comment by kbenoit** [comment] 2016-12-22 10:54
Wow - we do need to be careful about the indexing of tokens objects then. I could modify the `[` and `[[` methods to print something about the parent function, and then we could run all tests to see where this is being called. 

But I don't think parallelising dfm will help. The way that the dfm is constructed now comes very directly from the hash-indexed tokens object, and I even tested a method for doing this from the sparse column indexes directly (but it's not faster than the i, j, x triplet method). I doubt parallelising it will improve speed.

**Comment by koheiw** [comment] 2016-12-22 13:25
It is great if we could change the behaviors of functions according to the contexts, global or internal environment. Unclass in internal functions is also a solution. 

Anyway, we have to check all the functions with the Guardian corpus to make sure that none of them are terribly slow or memory hungry.

**Comment by methodds** [comment] 2016-12-26 19:34
I just wanted to quickly jump in and confirm dfm working pretty slow for me at the moment. Do you have a recommendation for large datasets?

**Comment by kbenoit** [comment] 2016-12-26 21:27
Did you try the latest GitHub version, since I think we fixed this in the most recent PR?

**Comment by methodds** [comment] 2016-12-27 11:09
With the most recent PR I have the following timings (CPU: i5-5300U):

```
# with word = 'fasterword'
txts_de <- dfm(filter(d, lang=='de' | lang == 'und') %>% .$text, stem=F, tolower=T,
            removeTwitter=F, removePunct=T,
            removeURL=F, removeNumbers=T, verbose=T,
            what='fasterword',
            remove=c(stopwords('german'), 'gibt', 'viele', 'wer',
                     'macht', 'ja', 'eigentlich', 'mehr', 'tun', 'wäre', 'https', 't.co'))

Creating a dfm from a character vector ...
   ... lowercasing
   ... tokenizing
   ... found 82,073 documents, 94,318 features
   ... removed 232 features, from 242 supplied (glob) feature types
   ... created a 82,073 x 94,086 sparse dfm
   ... complete. 
Elapsed time: 410 seconds.


# default
txts_de2 <- dfm(filter(d, lang=='de' | lang == 'und') %>% .$text, stem=F, tolower=T,
            removeTwitter=F, removePunct=T,
            removeURL=F, removeNumbers=T, verbose=T,
            remove=c(stopwords('german'), 'gibt', 'viele', 'wer',
                     'macht', 'ja', 'eigentlich', 'mehr', 'tun', 'wäre', 'https', 't.co'))

Creating a dfm from a character vector ...
   ... lowercasing
   ... tokenizing
   ... found 82,073 documents, 85,318 features
   ... removed 234 features, from 242 supplied (glob) feature types
   ... created a 82,073 x 85,084 sparse dfm
   ... complete. 
Elapsed time: 445 seconds.
```
What do you think? Are these reasonable timings for these corpus dimensions?

**Comment by koheiw** [comment] 2016-12-27 14:26
My fix for this problem is in dev_lookup branch, which is not yet merged to the master. Please try the branch, or wait until the branch is merged.

**Comment by kbenoit** [comment] 2016-12-27 19:00
I'm working on this now, but see http://stackoverflow.com/questions/41350665/why-does-classing-a-list-slow-down-the-lengths-function. @koheiw I don't think this is the main problem however, since the differences in `lengths()` on the classed and unclosed tokens objects are still just microseconds. 

@methodds It would be more informative to isolate the performance hit if you tokenize first (using `tokens()` and then try the dfm with and without the `remove` option.

**Comment by kbenoit** [comment] 2016-12-27 21:00
Take a look at the diff - @koheiw this has the same effect as unclassing the tokens object, but is far better since it preserves encapsulation.

(And follows the principle of minimal intervention to fix a problem!)

**Comment by methodds** [comment] 2017-01-10 09:31
I just tried the latest github version of quanteda and constructing a dfm raises the following error:

```
txts_en <- dfm(filter(d, lang == 'en' | lang == 'und') %>% .$text, 
          stem=F, tolower=T, verbose=T,
            removeTwitter=F, removePunct=T,
            removeURL=F, removeNumbers=T,
            remove=c(stopwords('english'), 'https', 't.co'))
Error in validObject(r) : 
  invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 24074
```

Unfortunately the dataset is somewhat large, do you know what's going on here without having the data to reproduce the error?

**Comment by kbenoit** [comment] 2017-01-10 09:36
Without being able to reproduce it, no, but try this:
1.  Send a simple character vector as `x`, don't complicate things for testing with `filter` and `%>%`.  
2.  remove the options, then try adding them back gradually to see if any or some combination is breaking things.  
3.  Try tokenising first using `tokens()` and see if that works as the argument to `dfm()`.

**Comment by methodds** [comment] 2017-01-10 10:15
Thanks for your quick response. After trying some of your suggestions I still do not understand what causes the error though. Please find a working space with the relevant character vectors [here](https://dl.dropboxusercontent.com/u/22352379/quanteda_dfm_error.RData).

Using the original vector still raises the error, without any options:

```
de <- filter(d, lang=='de' | lang == 'und') %>% .$text
typeof(de)
[1] "character"
txts_de <- dfm(de)

Error in validObject(r) : invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 24558
10.
stop(msg, ": ", errors, domain = NA)
9.
validObject(r)
8.
Matrix::sparseMatrix(i = index, p = cumsum(c(1, lengths(x))) - 1, x = 1L, dimnames = list(features = types, docs = names(x)))
7.
t(Matrix::sparseMatrix(i = index, p = cumsum(c(1, lengths(x))) - 1, x = 1L, dimnames = list(features = types, docs = names(x))))
6.
compile_dfm.tokens(x, verbose = verbose)
5.
compile_dfm(x, verbose = verbose)
4.
dfm.tokenizedTexts(tokenizedTexts, verbose = verbose, tolower = FALSE, stem = stem, remove = remove, select = select, thesaurus = thesaurus, dictionary = dictionary, valuetype = valuetype, startTime = startTime)
3.
dfm(tokenizedTexts, verbose = verbose, tolower = FALSE, stem = stem, remove = remove, select = select, thesaurus = thesaurus, dictionary = dictionary, valuetype = valuetype, startTime = startTime)
2.
dfm.character(de)
1.
dfm(de)

```
Using only a sample of the vector works with and without options:

```
> txts_de2 <- dfm(de2)
> 
> txts_de2 <- dfm(de2, stem=F, tolower=T,
+             removeTwitter=F, removePunct=T,
+             removeURL=F, removeNumbers=T, verbose=T,
+             remove=c(stopwords('german'), 'gibt', 'viele', 'wer',
+                      'macht', 'ja', 'eigentlich', 'mehr', 'tun', 'wäre', 'https', 't.co'))
Creating a dfm from a character vector ...
   ... lowercasing
   ... tokenizing
   ... found 5,000 documents, 10,783 features
   ... removed 207 features, from 242 supplied (glob) feature types
   ... created a 5,000 x 10,576 sparse dfm
   ... complete. 
Elapsed time: 0.266 seconds.
```

**Comment by koheiw** [comment] 2017-01-10 14:36
It looks like the issue #439 that I solved in the hotfix-439 branch. Please check if the number of unique types only increases in `tokens(de, verbose = TRUE)`.

**Comment by methodds** [comment] 2017-01-10 16:10
Sorry I don't quite understand what to do. After generating an object 
```de_tokens <- tokens(de, verbose = TRUE) ```, what code do I need afterwards?

**Comment by kbenoit** [comment] 2017-01-10 18:49
You didn't include `lang` in the object, so I cannot test that, but this works fine for me:

```r
> load("~/Downloads/quanteda_dfm_error.RData")
> require(quanteda)
> head(dfm(de))
Document-feature matrix of: 82,073 documents, 86,233 features (100% sparse).
(showing first 6 documents and first 6 features)
       features
docs    irgendwas schlimmes ist am #breitscheidplatz in
  text1         1         1   1  1                 1  1
  text2         0         0   0  0                 1  1
  text3         0         0   1  1                 1  1
  text4         0         0   0  0                 1  1
  text5         0         0   1  1                 1  1
  text6         0         0   1  1                 1  1
> head(dfm(de2))
Document-feature matrix of: 5,000 documents, 11,298 features (99.9% sparse).
(showing first 6 documents and first 6 features)
       features
docs    #prayforberlin \U0001f64f der is hat ein
  text1              1          1   0  0   0   0
  text2              0          0   1  1   1   1
  text3              0          0   0  0   0   0
  text4              0          0   0  0   0   0
  text5              1          0   0  0   0   0
  text6              1          0   0  0   0   0
```

**Comment by koheiw** [comment] 2017-01-10 18:52
You will have more flexibility if you use `tokens()` function before `dfm()`.
```
de_tokens <- tokens(de, verbose = TRUE)
dfm(de_tokens)
```

**Comment by kbenoit** [comment] 2017-01-10 18:54
@methodds Does this display the same on your system? In case this is an encoding issue.

```r
> cat(featnames(dfm(de2))[2])
🙏
```

**Comment by methodds** [comment] 2017-01-10 19:04
in ```RStudio``` I can't actually see the special character but only '#PrayForBerlin', but if I copy pase it here it works:

````
cat(featnames(dfm(de2))[2])
🙏
> 
````
I'm confused... =D

**Comment by methodds** [comment] 2017-01-10 19:19
Sorry for the double post, but I guess editing one post 2304980 times might also be annoying for you to work with. So I just realized that the special charracter is still there on my linux system, but just not displayed in the console properly. Otherwise the matric wouldn't have 6 columns but only 5:
````
`head(dfm(de2))
Document-feature matrix of: 5,000 documents, 11,298 features (99.9% sparse).
(showing first 6 documents and first 6 features)
       features
docs    #prayforberlin der is hat ein
  text1              1 1   0  0   0   0
````

On my windows machine it looks like this:
````
 head(dfm(de2))
Document-feature matrix of: 5,000 documents, 11,298 features (99.9% sparse).
(showing first 6 documents and first 6 features)
       features
docs    #prayforberlin       \xf0\u009f\u0099\u008f der is hat ein
  text1              1                            1   0  0   0   0
````
Regardless, on neither of the two machines (both with the latest github version) does ````head(dfm(de))```` work without an error.

**Comment by kbenoit** [comment] 2017-01-10 19:34
We've pinpointed it now - it's a bug caused by #438 - we are working on a solution.

**Comment by kbenoit** [comment] 2017-01-11 10:48
Should be fixed now @methodds please give it a try with v0.9.9-4.

**Comment by methodds** [comment] 2017-01-11 14:32
yep it works now, thank you :)

**Closed** 2017-01-11 14:33 UTC
Labels: performance
